language: java

jdk: openjdk8

install: ./gradlew clean jar

script:
  - ./gradlew test

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

stages:
  - test-jdk-8
  - test-jdk-9

jobs:
  include:
    - stage: test-jdk-8
      name: "test-jdk-8"
      jdk: openjdk8
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/ui check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-8
      name: "test-jdk-8"
      jdk: openjdk8
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/cart check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-8
      name: "test-jdk-8"
      jdk: openjdk8
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/user check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-8
      name: "test-jdk-8"
      jdk: openjdk8
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/order check
      env:
        - COVERAGE=0.25

    - stage: test-jdk-8
      name: "test-jdk-8"
      jdk: openjdk8
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/cart check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-8
      name: "test-jdk-8"
      jdk: openjdk8
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/product check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-8
      name: "test-jdk-8"
      jdk: openjdk8
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/user check
      env:
        - COVERAGE=0.25

    - stage: test-jdk-9
      name: "test-jdk-9"
      jdk: openjdk9
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/ui check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-9
      name: "test-jdk-9"
      jdk: openjdk9
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/cart check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-9
      name: "test-jdk-9"
      jdk: openjdk9
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/user check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-9
      name: "test-jdk-9"
      jdk: openjdk9
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/order check
      env:
        - COVERAGE=0.25

    - stage: test-jdk-9
      name: "test-jdk-9"
      jdk: openjdk9
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/cart check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-9
      name: "test-jdk-9"
      jdk: openjdk9
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/product check
      env:
        - COVERAGE=0.5

    - stage: test-jdk-9
      name: "test-jdk-9"
      jdk: openjdk9
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/user check
      env:
        - COVERAGE=0.25

deploy:
  - provider: script
    script: echo 'WTP'
    on:
      all_branches: true
